project:
  type: website
  output-dir: docs 

website:
  title: "Odile Gabbiani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - hiking.qmd

format:
  html:
    page-layout: full
    theme: minty
    mainfont: Ubuntu
    css: styles.css
    toc: true

editor: visual

